In [5]:
import numpy as np

In [6]:
dizim=np.arange(0,15)

In [7]:
dizim[3:7]=-8 # 3. ve 6. indeksler arası tüm indexleri -5 yapar

In [8]:
dizi2=np.arange(0,20)
sliceing = dizi2[4:9]
sliceing

array([4, 5, 6, 7, 8])

In [9]:
sliceing[:]=700 # tüm elemanlar 700 olur
sliceing

array([700, 700, 700, 700, 700])

In [10]:
ornek=sliceing.copy()
ornek

array([700, 700, 700, 700, 700])

## Matrix İndexler

In [12]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]
matris = np.array(benimListem)
print(matris)
matris[0][0]
matris[1,2]

[[10 20 30]
 [20 30 40]
 [40 50 60]]


40

In [22]:
matris[0:,0:1]

array([[10],
       [20],
       [40]])