In [7]:
import numpy as np
listem=[20,30,40,50]
np.array(listem)

array([20, 30, 40, 50])

In [8]:
matrixList=[[10,20,30],[20,30,40],[40,50,60]]
print(np.array(matrixList))

[[10 20 30]
 [20 30 40]
 [40 50 60]]
