## Arange

In [4]:
import numpy as np
print(list(range(0,10)))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [40]:
print(np.arange(0,21,2))
benimNumpyDizim = np.arange(30)

[ 0  2  4  6  8 10 12 14 16 18 20]


## Zeros

In [25]:
print(np.zeros((5,5))) ##5 e 5 lik 0 dizisi

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
print(np.ones((3,3))) # 3 e 3 lük 1 dizisi

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Linspace

In [27]:
print(np.linspace(0,50,6)) #0 dan 50 ye kadar arasındaki fark eşit 6 sayı

[ 0. 10. 20. 30. 40. 50.]


## Eye

In [29]:
np.eye(5) #birim matris

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

In [42]:
np.random.randn(4,4) #4 e 4 bir matris olustururnp.random.randint(1,10) #tek bir int dondurur
benimRandomDizim = np.random.randint(1,100,30) #1 le 100 arası 30 değer

# Numpy Dizi Metodları

In [45]:
print(benimNumpyDizim.reshape(5,6)) # 5e 6 lık bir array

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [46]:
benimNumpyDizim.max()

29

In [49]:
benimNumpyDizim.argmax()#max sayının index i verir

29

In [51]:
benimNumpyDizim.shape #güncel dizinin şeklini gösterir

(30,)