In [1]:
import numpy as np

In [5]:
dizi = np.random.randint(1,100,25)

In [18]:
matris = dizi.reshape(5,5)
print(matris)

[[ 3 86 16 97 39]
 [67 27 93 62  3]
 [83 61 15 55 27]
 [43 62 74 95 84]
 [50 19 53 84 51]]


In [27]:
sonucDizisi= dizi>24

In [31]:
dizi[sonucDizisi]

array([86, 97, 39, 67, 27, 93, 62, 83, 61, 55, 27, 43, 62, 74, 95, 84, 50,
       53, 84, 51])

In [35]:
dizi/dizi
dizi + dizi
dizi - dizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [38]:
np.sqrt(dizi) #karekok alır

array([1.73205081, 9.2736185 , 4.        , 9.8488578 , 6.244998  ,
       8.18535277, 5.19615242, 9.64365076, 7.87400787, 1.73205081,
       9.11043358, 7.81024968, 3.87298335, 7.41619849, 5.19615242,
       6.55743852, 7.87400787, 8.60232527, 9.74679434, 9.16515139,
       7.07106781, 4.35889894, 7.28010989, 9.16515139, 7.14142843])